### Test Login
# Login
POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "luigi.derussis@polito.it",
  "password": "testtest"
}
###

GET http://localhost:3001/api/1/history
###

GET http://localhost:3001/images/img1.jpg
###

### Checking if user is still logged-in.
GET http://localhost:3001/api/sessions/current
###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current
###

GET http://localhost:3001/api/image
###

POST http://localhost:3001/api/meme
Content-Type: application/json

{
  "usedImageIds": [1]
}
###

POST http://localhost:3001/api/meme/verify
content-type: application/json

{
  "imageId": 2,
  "captionId": 2
}
###

GET   http://localhost:3001/api/image/1/captions
###

POST http://localhost:3001/api/meme/correct-captions
content-type: application/json

{
  "imageId": 1
}
###

POST http://localhost:3001/api/games/1/rounds
content-type: application/json

{
  "imageId": 1,
  "selectedCaptionId":1
}
###

POST http://localhost:3001/api/complete-game
content-type: application/json

{
  "userId": 1,
  "score": 1,
  "rounds": [
    {
        "meme_id": 1,
        "selected_caption": null,
        "correct": true
    },
    {
        "meme_id": 2,
        "selected_caption": 2,
        "correct": true
    },
    {
        "meme_id": 3,
        "selected_caption": 3,
        "correct": true
    }
  ]
}
###

PUT http://localhost:3001/api/games/2/end
content-type: application/json

{
  "score": 15
}
###

GET http://localhost:3001/api/games/7/summary
###

GET http://localhost:3001/api/1/history
###


### Request a new meme with no used images
POST http://localhost:3001/api/meme
content-type: application/json

{
  "usedImageIds": [2]
}
###

